import createClient from "openapi-fetch";

import type { paths } from "@/lib/api/schema";

/**
 * Typed OpenAPI client. Schema is regenerated by `pnpm generate:api`.
 *
 * `baseUrl` is `/` because Next.js rewrites `/api/*` to the backend
 * (see `next.config.ts`). Same-origin in dev and prod, no CORS in dev.
 */
export const apiClient = createClient<paths>({
  baseUrl: "/",
});
